CREATE TABLE [dbo].[Posts]
(
    Id INT NOT NULL PRIMARY KEY IDENTITY,
    Title NVARCHAR(200) NOT NULL,
    Content NVARCHAR(MAX) NOT NULL,
    UserId INT NOT NULL,
    DateCreated DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT FK_Posts_Users FOREIGN KEY (UserId) REFERENCES dbo.Users(Id)
)
